FROM centos/systemd
RUN yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute ca-certificates && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all;
RUN LC_CTYPE=en_US.UTF-8 && export LC_CTYPE;
RUN yum install --assumeyes python3-pip

CMD ["/sbin/init"]