FROM centos/systemd

RUN yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute ca-certificates python-apt aptitude python3.8 python3.8 python3-distutils curl libpq-dev build-essential python3.8-dev && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf  && yum clean all;

RUN ln -s /usr/bin/python3.8 /usr/bin/python3
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.8 get-pip.py
RUN pip3.8 install --upgrade pip

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
ENV PYTHONPATH "${PYTHONPATH}:."
RUN pip3 install --trusted-host pypi.python.org ansible

CMD ["/sbin/init"]