---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: omero-onenode
    image: eniocarboni/docker-ubuntu-systemd:22.04
    image_version: latest
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
    groups:
      - docker-hosts
      - omero-py3
provisioner:
  name: ansible
  playbooks:
    prepare: ../prepare.yml
    converge: ../../playbook.yml
  options:
    v: true
    diff: true
  inventory:
    host_vars:
      ome-demoserver:
        postgresql_version: "16"
        omero_server_selfsigned_certificates: true
        omero_server_dbhost: localhost
        omero_server_dbuser: demo
        omero_server_dbname: omero
        omero_server_dbpassword: omero
        omero_server_mail_from: example.com
        omero_server_mail_host: localhost
        omero_server_rootpassword: omero
  lint:
    name: ansible-lint
scenario:
  name: ubuntu2204
  test_sequence:
    # dependency must come first, otherwise the first "destroy" errors
    - dependency
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # FIXME: Some tasks are not idempotent
    # - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  directory: ../resources/tests/
